[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build && pnpm drizzle-kit generate && pnpm drizzle-kit migrate"]

[start]
cmd = "node seed-db.mjs; node dist/index.js"

[variables]
NODE_ENV = "production"
